CREATE TABLE S_EMP_COPY (
  ID             NUMBER(7, 0),
  LAST_NAME      VARCHAR2(25 BYTE) NOT NULL,
  FIRST_NAME     VARCHAR2(25 BYTE),
  TITLE          VARCHAR2(50 BYTE),
  DEPT_ID        NUMBER(7, 0),
  SALARY         NUMBER(11, 2)
);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (1, 'Velasquez', 'Carmen', 'President', 1, 2000);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (2, 'Ngao', 'LaDoris', 'VP. Operations', 2, 1450);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (3, 'Nagayamn', 'Midori', 'VP, Sales', 3, 1400);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (4, 'Urguhart', 'Molly', 'Warehouse Manager', 6, 1200);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (5, 'Nozaki', 'Akira', 'Stock Clerk', 16, 1200);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (6, 'Maduro', 'Elena', 'Stock Clerk', 14, 1400);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (7, 'Newman', 'Chad', 'Stock Clerk', 43, 750);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (8, 'Smith', 'George', 'Stok Clerk', 15, 940);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (9, 'Patel', 'Radha', 'Stoc Clerk', 34, 795);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (10, 'Patel', 'Vikram', 'Stock Clerk', 42, 750);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (11, 'Menchu', 'Robertn', 'Warеhouse Manager', 7, 1250);
INSERT INTO S_EMP_COPY (ID, LAST_NAME, FIRST_NAME, TITLE, DEPT_ID, SALARY)
VALUES (12, 'Havel', 'Marta', 'Warehouse Manager', 10, 1307);
Create table s_title
As
Select distinct title from s_emp;